[tool.poetry]
name = "energymanagementrl"
version = "0.1.0"
description = "Using RL to controll huawei fusion solar inverter and maximize energy production"
authors = ["emanuele <emanuele.rapisarda.1997@gmail.com >"]
readme = "README.md"

[tool.poetry.dependencies]
gymnasium = "0.29.1"
pandas = "2.2.3"
stable-baselines3 = "2.5.0a0"
matplotlib = "3.9.3"
fonttools = "4.54.1"
scipy = "1.14.1"

[project]
license = {file = "LICENSE"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
