[tool.poetry]
name = "energymanagementrl"
version = "0.1.0"
description = "Using RL to controll huawei fusion solar inverter and maximize energy production"
authors = ["emanuele <emanuele.rapisarda.1997@gmail.com >"]
readme = "README.md"


[project]
license = {file = "LICENSE"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
