name: Check & Refresh Kaggle Notebook

on:
#  schedule:
#    - cron: "0,30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  check-and-refresh:
    runs-on: ubuntu-latest
    environment: test

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      KAGGLE_KERNEL: ${{ secrets.KAGGLE_USERNAME }}/${{ vars.KAGGLE_NOTEBOOK_ID }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: pip install --quiet kaggle

      - name: Get notebook status
        id: get_status
        run: |
          STATUS_OUTPUT=$(kaggle kernels status "$KAGGLE_KERNEL")
          STATUS=$(echo "$STATUS_OUTPUT" | sed -n 's/.*status "\([^"]*\)".*/\1/p')

          if [[ -z "$STATUS" ]]; then
            echo "Error: Failed to retrieve notebook status." >&2
            exit 1
          fi

          echo "notebook_status=$STATUS" >> $GITHUB_OUTPUT

      - name: Pull and push notebook if not running
        if: steps.get_status.outputs.notebook_status != 'KernelWorkerStatus.RUNNING'
        run: |
          kaggle kernels pull "$KAGGLE_KERNEL" -m --path .
          kaggle kernels push --path .
