name: Refresh Kaggle Notebook

on:
#  schedule:
#    - cron: '0 11,23 * * *' # Runs at 11:00 and 23:00 UTC daily
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    environment: test

    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      KAGGLE_KERNEL: ${{ secrets.KAGGLE_USERNAME }}/${{vars.KAGGLE_NOTEBOOK_ID}}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: pip install --quiet kaggle

      - name: Pull notebook
        run: |
          echo "[$(date)] Pulling latest version of $KAGGLE_KERNEL"
          kaggle kernels pull "$KAGGLE_KERNEL" -m --path .

      - name: Push notebook
        run: |
          echo "[$(date)] Pushing updated notebook to Kaggle"
          kaggle kernels push --path .
